INSERT INTO CLIENTE (NOME_CLIENTE) VALUES ('Cliente1');
INSERT INTO CLIENTE (NOME_CLIENTE) VALUES ('Cliente2');

INSERT INTO PEDIDO (NUMERO_CONTROLE, DATA_CADASTRO, NOME_PRODUTO, VALOR_UNITARIO, QUANTIDADE, VALOR_TOTAL, ID_CLIENTE)
VALUES ('123', '2022-01-01', 'Produto1', 10.0, 2, 20.0, 1);

INSERT INTO PEDIDO (NUMERO_CONTROLE, DATA_CADASTRO, NOME_PRODUTO, VALOR_UNITARIO, QUANTIDADE, VALOR_TOTAL, ID_CLIENTE)
VALUES ('456', '2022-01-01', 'Produto2', 15.0, 3, 45.0, 2);